### ISSUE TITLE
ToolboxRepository .json file missing

### ISSUE THREAD

**Issue by mdefende** [gkaguirrelab/eyeTrackTOMEAnalysis#16]
Hi all,

Whenever I run the functions in this toolbox that call the tbUse function, it errors out due to there not being a repository json file in ToolboxRepository, at least currently on github. I've currently commented those calls out to ignore it for now. Just wondering if this repo should be available via tbUse or not. Thanks

**Comment by gkaguirre** [comment]
Hi Matt. This repository is a "project" as opposed to a "toolbox". The toolboxToolbox command you need is `tbUseProject('eyeTrackTOMEAnalysis')`.
